buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'http://dl.google.com/dl/android/maven2/'; allowInsecureProtocol = true }
        maven { url 'http://repo.maven.apache.org/maven2/'; allowInsecureProtocol = true }
        maven { url 'http://plugins.gradle.org/m2/'; allowInsecureProtocol = true }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'http://dl.google.com/dl/android/maven2/'; allowInsecureProtocol = true }
        maven { url 'http://repo.maven.apache.org/maven2/'; allowInsecureProtocol = true }
        maven { url 'http://plugins.gradle.org/m2/'; allowInsecureProtocol = true }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
